version: '3.8'
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=zeeshan
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      # RabbitMQ instance
      - '5672:5672'
      # Web Interface
      - '15672:15672'
 